# Generated by Django 2.0.5 on 2018-09-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=25)),
            ],
        ),
    ]
